// stars.js - База данных 30 самых известных звёзд
export const STARS_DATA = {
    "Солнце": {
        order: 1,
        type: "Жёлтый карлик (G2V)",
        radius: 1,           // В радиусах Солнца
        mass: 1,             // В массах Солнца
        luminosity: 1,       // В светимостях Солнца
        temperature: 5778,   // Кельвины (поверхность)
        distance: 0.000016,  // Световых лет
        age: 4.6,            // Миллиардов лет
        color: "#FFF5E0",
        coronaColor: "#FFE4B5",
        spectralClass: "G2V",
        constellation: "—",
        info: {
            diameter: "1 392 700 км",
            diamSun: "1.00",
            mass: "1.989 × 10³⁰ кг",
            massSun: "1.00",
            luminosity: "3.828 × 10²⁶ Вт",
            lumSun: "1.00",
            temperature: "5 778 K",
            tempClass: "Жёлтый",
            density: "1.41 г/см³",
            gravity: "274 м/с²",
            rotation: "25.4 дня",
            age: "4.6 млрд лет",
            dist: "8.3 световых минуты",
            composition: "73% H, 25% He"
        },
        facts: [
            "Солнце содержит 99.86% всей массы Солнечной системы.",
            "Каждую секунду Солнце преобразует 600 миллионов тонн водорода в гелий.",
            "Свет от Солнца достигает Земли за 8 минут 20 секунд.",
            "Температура ядра Солнца достигает 15 миллионов градусов Цельсия.",
            "Солнце — одна из 200-400 миллиардов звёзд в нашей галактике."
        ]
    },
    "Сириус A": {
        order: 2,
        type: "Белая звезда главной последовательности (A1V)",
        radius: 1.711,
        mass: 2.063,
        luminosity: 25.4,
        temperature: 9940,
        distance: 8.6,
        age: 0.242,
        color: "#CAE8FF",
        coronaColor: "#A0D4FF",
        spectralClass: "A1V",
        constellation: "Большой Пёс",
        info: {
            diameter: "2 381 000 км",
            diamSun: "1.71",
            mass: "4.10 × 10³⁰ кг",
            massSun: "2.06",
            luminosity: "9.73 × 10²⁷ Вт",
            lumSun: "25.4",
            temperature: "9 940 K",
            tempClass: "Бело-голубой",
            density: "0.57 г/см³",
            gravity: "896 м/с²",
            rotation: "16 часов",
            age: "242 млн лет",
            dist: "8.6 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Сириус — самая яркая звезда на ночном небе Земли.",
            "Имеет белого карлика-компаньона — Сириус B.",
            "Древние египтяне связывали появление Сириуса с разливом Нила.",
            "Название происходит от греческого «сейриос» — «палящий».",
            "Сириус в 25 раз ярче Солнца, но это близко к нам."
        ]
    },
    "Канопус": {
        order: 3,
        type: "Жёлто-белый сверхгигант (F0Ib)",
        radius: 71,
        mass: 8.0,
        luminosity: 10700,
        temperature: 7350,
        distance: 310,
        age: 0.025,
        color: "#FFF8E7",
        coronaColor: "#FFE9B8",
        spectralClass: "F0Ib",
        constellation: "Киль",
        info: {
            diameter: "98 800 000 км",
            diamSun: "71",
            mass: "1.59 × 10³¹ кг",
            massSun: "8.0",
            luminosity: "4.1 × 10³⁰ Вт",
            lumSun: "10 700",
            temperature: "7 350 K",
            tempClass: "Жёлто-белый",
            density: "0.00004 г/см³",
            gravity: "4.3 м/с²",
            rotation: "~8 лет",
            age: "25 млн лет",
            dist: "310 св. лет",
            composition: "Водород, Гелий, Углерод"
        },
        facts: [
            "Канопус — вторая по яркости звезда ночного неба.",
            "Используется как навигационный ориентир для космических аппаратов.",
            "Абсолютная светимость в 10 700 раз больше солнечной.",
            "Была полярной звездой для южного полюса 14 000 лет назад.",
            "Названа в честь кормчего Менелая из греческой мифологии."
        ]
    },
    "Альфа Центавра A": {
        order: 4,
        type: "Жёлтый карлик (G2V)",
        radius: 1.2234,
        mass: 1.1,
        luminosity: 1.519,
        temperature: 5790,
        distance: 4.37,
        age: 5.3,
        color: "#FFF5E0",
        coronaColor: "#FFE4B5",
        spectralClass: "G2V",
        constellation: "Центавр",
        info: {
            diameter: "1 703 000 км",
            diamSun: "1.22",
            mass: "2.19 × 10³⁰ кг",
            massSun: "1.10",
            luminosity: "5.82 × 10²⁶ Вт",
            lumSun: "1.52",
            temperature: "5 790 K",
            tempClass: "Жёлтый",
            density: "1.08 г/см³",
            gravity: "306 м/с²",
            rotation: "22 дня",
            age: "5.3 млрд лет",
            dist: "4.37 св. лет",
            composition: "73% H, 25% He"
        },
        facts: [
            "Ближайшая к Солнцу звезда, похожая на него по типу.",
            "Часть тройной звёздной системы Альфа Центавра.",
            "Свет от неё достигает Земли за 4.37 года.",
            "Возраст системы оценивается в 5-6 миллиардов лет.",
            "Потенциальная цель для межзвёздных миссий."
        ]
    },
    "Арктур": {
        order: 5,
        type: "Оранжевый гигант (K1.5III)",
        radius: 25.4,
        mass: 1.08,
        luminosity: 170,
        temperature: 4286,
        distance: 36.7,
        age: 7.1,
        color: "#FFB347",
        coronaColor: "#FF9933",
        spectralClass: "K1.5III",
        constellation: "Волопас",
        info: {
            diameter: "35 400 000 км",
            diamSun: "25.4",
            mass: "2.15 × 10³⁰ кг",
            massSun: "1.08",
            luminosity: "6.51 × 10²⁸ Вт",
            lumSun: "170",
            temperature: "4 286 K",
            tempClass: "Оранжевый",
            density: "0.00016 г/см³",
            gravity: "4.5 м/с²",
            rotation: "~2 года",
            age: "7.1 млрд лет",
            dist: "36.7 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Арктур — самая яркая звезда северного полушария неба.",
            "Движется со скоростью 122 км/с относительно Солнца.",
            "Вероятно, пришла из другой галактики, поглощённой Млечным Путём.",
            "Её свет использовали для открытия Всемирной выставки 1933 года.",
            "Название означает «страж медведя» на греческом."
        ]
    },
    "Вега": {
        order: 6,
        type: "Белая звезда главной последовательности (A0V)",
        radius: 2.362,
        mass: 2.135,
        luminosity: 40.12,
        temperature: 9602,
        distance: 25.04,
        age: 0.455,
        color: "#D4E9FF",
        coronaColor: "#B8DCFF",
        spectralClass: "A0V",
        constellation: "Лира",
        info: {
            diameter: "3 290 000 км",
            diamSun: "2.36",
            mass: "4.25 × 10³⁰ кг",
            massSun: "2.14",
            luminosity: "1.54 × 10²⁸ Вт",
            lumSun: "40.1",
            temperature: "9 602 K",
            tempClass: "Бело-голубой",
            density: "0.36 г/см³",
            gravity: "464 м/с²",
            rotation: "12.5 часов",
            age: "455 млн лет",
            dist: "25 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Вега была северной полярной звездой 12 000 лет назад и станет снова.",
            "Быстро вращается — один оборот за 12.5 часов.",
            "Служила эталоном звёздной величины 0.0 в астрономии.",
            "Окружена диском пыли — возможно, строящаяся планетная система.",
            "Одна из вершин Летне-осеннего треугольника."
        ]
    },
    "Капелла": {
        order: 7,
        type: "Жёлтый гигант (G3III/G0III)",
        radius: 11.98,
        mass: 2.57,
        luminosity: 78.7,
        temperature: 4970,
        distance: 42.9,
        age: 0.59,
        color: "#FFE4B5",
        coronaColor: "#FFD699",
        spectralClass: "G3III",
        constellation: "Возничий",
        info: {
            diameter: "16 700 000 км",
            diamSun: "12.0",
            mass: "5.11 × 10³⁰ кг",
            massSun: "2.57",
            luminosity: "3.01 × 10²⁸ Вт",
            lumSun: "78.7",
            temperature: "4 970 K",
            tempClass: "Жёлтый",
            density: "0.015 г/см³",
            gravity: "48 м/с²",
            rotation: "104 дня",
            age: "590 млн лет",
            dist: "42.9 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Капелла — четверная звёздная система из двух пар звёзд.",
            "Шестая по яркости звезда на ночном небе.",
            "Название означает «козочка» на латыни.",
            "Две главные звезды обращаются друг вокруг друга за 104 дня.",
            "Одна из первых звёзд, у которой измерили угловой диаметр."
        ]
    },
    "Ригель": {
        order: 8,
        type: "Голубой сверхгигант (B8Ia)",
        radius: 78.9,
        mass: 21,
        luminosity: 120000,
        temperature: 12100,
        distance: 860,
        age: 0.008,
        color: "#B8D4FF",
        coronaColor: "#8FC0FF",
        spectralClass: "B8Ia",
        constellation: "Орион",
        info: {
            diameter: "109 900 000 км",
            diamSun: "78.9",
            mass: "4.18 × 10³¹ кг",
            massSun: "21",
            luminosity: "4.60 × 10³¹ Вт",
            lumSun: "120 000",
            temperature: "12 100 K",
            tempClass: "Голубой",
            density: "0.00001 г/см³",
            gravity: "9.4 м/с²",
            rotation: "~1 год",
            age: "8 млн лет",
            dist: "860 св. лет",
            composition: "Водород, Гелий, Азот"
        },
        facts: [
            "Ригель — седьмая по яркости звезда на небе.",
            "Если бы был на месте Солнца, его диск занял бы пол неба.",
            "Является тройной или даже четверной звёздной системой.",
            "Излучает столько энергии за час, сколько Солнце за месяц.",
            "Название происходит от арабского «нога» (Ориона)."
        ]
    },
    "Процион A": {
        order: 9,
        type: "Жёлто-белый субгигант (F5IV-V)",
        radius: 2.048,
        mass: 1.499,
        luminosity: 6.93,
        temperature: 6530,
        distance: 11.46,
        age: 1.87,
        color: "#FFF8E7",
        coronaColor: "#FFF0D0",
        spectralClass: "F5IV-V",
        constellation: "Малый Пёс",
        info: {
            diameter: "2 850 000 км",
            diamSun: "2.05",
            mass: "2.98 × 10³⁰ кг",
            massSun: "1.50",
            luminosity: "2.65 × 10²⁷ Вт",
            lumSun: "6.93",
            temperature: "6 530 K",
            tempClass: "Жёлто-белый",
            density: "0.28 г/см³",
            gravity: "112 м/с²",
            rotation: "23 дня",
            age: "1.87 млрд лет",
            dist: "11.5 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Процион — восьмая по яркости звезда ночного неба.",
            "Имеет белого карлика-компаньона — Процион B.",
            "Название означает «перед собакой» — восходит перед Сириусом.",
            "Одна из ближайших к Солнцу звёзд.",
            "Входит в Зимний треугольник вместе с Бетельгейзе и Сириусом."
        ]
    },
    "Бетельгейзе": {
        order: 10,
        type: "Красный сверхгигант (M1-M2Ia-ab)",
        radius: 887,
        mass: 16.5,
        luminosity: 126000,
        temperature: 3600,
        distance: 700,
        age: 0.01,
        color: "#FF6B4A",
        coronaColor: "#FF4A30",
        spectralClass: "M2Iab",
        constellation: "Орион",
        info: {
            diameter: "1 234 000 000 км",
            diamSun: "887",
            mass: "3.28 × 10³¹ кг",
            massSun: "16.5",
            luminosity: "4.83 × 10³¹ Вт",
            lumSun: "126 000",
            temperature: "3 600 K",
            tempClass: "Красный",
            density: "0.000001 г/см³",
            gravity: "0.06 м/с²",
            rotation: "~36 лет",
            age: "10 млн лет",
            dist: "700 св. лет",
            composition: "Водород, Гелий, тяжёлые элементы"
        },
        facts: [
            "Бетельгейзе — один из крупнейших известных красных сверхгигантов.",
            "На месте Солнца её поверхность достигла бы орбиты Юпитера.",
            "Взорвётся как сверхновая в ближайшие 100 000 лет.",
            "Размеры звезды меняются со временем — она «дышит».",
            "Название происходит от арабского «подмышка охотника»."
        ]
    },
    "Ахернар": {
        order: 11,
        type: "Голубая звезда главной последовательности (B6Vep)",
        radius: 7.3,
        mass: 6.7,
        luminosity: 3150,
        temperature: 14500,
        distance: 139,
        age: 0.037,
        color: "#9FC5FF",
        coronaColor: "#7EAFFF",
        spectralClass: "B6Vep",
        constellation: "Эридан",
        info: {
            diameter: "10 200 000 км",
            diamSun: "7.3",
            mass: "1.33 × 10³¹ кг",
            massSun: "6.7",
            luminosity: "1.21 × 10³⁰ Вт",
            lumSun: "3 150",
            temperature: "14 500 K",
            tempClass: "Голубой",
            density: "0.024 г/см³",
            gravity: "346 м/с²",
            rotation: "~2 дня",
            age: "37 млн лет",
            dist: "139 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Ахернар — самая плоская звезда из известных.",
            "Вращается так быстро, что экватор шире полюсов на 56%.",
            "Девятая по яркости звезда ночного неба.",
            "Название означает «конец реки» на арабском.",
            "Южная точка созвездия Эридан."
        ]
    },
    "Хадар": {
        order: 12,
        type: "Голубой гигант (B1III)",
        radius: 9,
        mass: 12.02,
        luminosity: 41700,
        temperature: 25000,
        distance: 390,
        age: 0.014,
        color: "#A0C8FF",
        coronaColor: "#80B4FF",
        spectralClass: "B1III",
        constellation: "Центавр",
        info: {
            diameter: "12 500 000 км",
            diamSun: "9.0",
            mass: "2.39 × 10³¹ кг",
            massSun: "12.0",
            luminosity: "1.60 × 10³¹ Вт",
            lumSun: "41 700",
            temperature: "25 000 K",
            tempClass: "Голубой",
            density: "0.023 г/см³",
            gravity: "408 м/с²",
            rotation: "~3 дня",
            age: "14 млн лет",
            dist: "390 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Хадар — тройная звёздная система.",
            "Вторая по яркости звезда в созвездии Центавра.",
            "Одиннадцатая по яркости звезда ночного неба.",
            "Вместе с Альфой Центавра указывает на Южный Крест.",
            "Будет сверхновой через несколько миллионов лет."
        ]
    },
    "Альтаир": {
        order: 13,
        type: "Белая звезда главной последовательности (A7V)",
        radius: 1.79,
        mass: 1.79,
        luminosity: 10.6,
        temperature: 7670,
        distance: 16.73,
        age: 1.2,
        color: "#E8F4FF",
        coronaColor: "#D0E8FF",
        spectralClass: "A7V",
        constellation: "Орёл",
        info: {
            diameter: "2 490 000 км",
            diamSun: "1.79",
            mass: "3.56 × 10³⁰ кг",
            massSun: "1.79",
            luminosity: "4.06 × 10²⁷ Вт",
            lumSun: "10.6",
            temperature: "7 670 K",
            tempClass: "Белый",
            density: "0.44 г/см³",
            gravity: "175 м/с²",
            rotation: "8.9 часов",
            age: "1.2 млрд лет",
            dist: "16.7 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Альтаир — одна из вершин Летне-осеннего треугольника.",
            "Один из самых быстро вращающихся объектов — оборот за 9 часов.",
            "Из-за вращения сплюснута на 14%.",
            "Одна из первых звёзд, сфотографированных как диск.",
            "Название означает «летящий орёл» на арабском."
        ]
    },
    "Акрукс": {
        order: 14,
        type: "Голубая звезда (B0.5IV + B1V)",
        radius: 7.8,
        mass: 17.8,
        luminosity: 25000,
        temperature: 28000,
        distance: 320,
        age: 0.011,
        color: "#9EC5FF",
        coronaColor: "#7EB0FF",
        spectralClass: "B0.5IV",
        constellation: "Южный Крест",
        info: {
            diameter: "10 900 000 км",
            diamSun: "7.8",
            mass: "3.54 × 10³¹ кг",
            massSun: "17.8",
            luminosity: "9.57 × 10³⁰ Вт",
            lumSun: "25 000",
            temperature: "28 000 K",
            tempClass: "Голубой",
            density: "0.05 г/см³",
            gravity: "798 м/с²",
            rotation: "~1 день",
            age: "11 млн лет",
            dist: "320 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Акрукс — самая яркая звезда Южного Креста.",
            "На самом деле это тройная звёздная система.",
            "Изображена на флагах Австралии, Новой Зеландии и Бразилии.",
            "Название — сокращение от «Альфа Южного Креста».",
            "Тринадцатая по яркости звезда ночного неба."
        ]
    },
    "Альдебаран": {
        order: 15,
        type: "Оранжевый гигант (K5III)",
        radius: 44.13,
        mass: 1.16,
        luminosity: 518,
        temperature: 3910,
        distance: 65.3,
        age: 6.6,
        color: "#FF9B4A",
        coronaColor: "#FF8033",
        spectralClass: "K5III",
        constellation: "Телец",
        info: {
            diameter: "61 400 000 км",
            diamSun: "44.1",
            mass: "2.31 × 10³⁰ кг",
            massSun: "1.16",
            luminosity: "1.98 × 10²⁹ Вт",
            lumSun: "518",
            temperature: "3 910 K",
            tempClass: "Оранжевый",
            density: "0.00002 г/см³",
            gravity: "1.6 м/с²",
            rotation: "~520 дней",
            age: "6.6 млрд лет",
            dist: "65 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Альдебаран — глаз Тельца в созвездии.",
            "Название означает «последователь» — идёт за Плеядами.",
            "Pioneer 10 движется в его направлении, прибудет через 2 млн лет.",
            "Кажется частью скопления Гиады, но находится вдвое ближе.",
            "Четырнадцатая по яркости звезда ночного неба."
        ]
    },
    "Антарес": {
        order: 16,
        type: "Красный сверхгигант (M1.5Iab-Ib)",
        radius: 680,
        mass: 12,
        luminosity: 75900,
        temperature: 3660,
        distance: 550,
        age: 0.015,
        color: "#FF5733",
        coronaColor: "#FF3311",
        spectralClass: "M1.5Iab",
        constellation: "Скорпион",
        info: {
            diameter: "946 000 000 км",
            diamSun: "680",
            mass: "2.39 × 10³¹ кг",
            massSun: "12",
            luminosity: "2.91 × 10³¹ Вт",
            lumSun: "75 900",
            temperature: "3 660 K",
            tempClass: "Красный",
            density: "0.000001 г/см³",
            gravity: "0.07 м/с²",
            rotation: "~20 лет",
            age: "15 млн лет",
            dist: "550 св. лет",
            composition: "Водород, Гелий, тяжёлые элементы"
        },
        facts: [
            "Антарес — «соперник Марса», красный как планета.",
            "На месте Солнца достиг бы орбиты Марса.",
            "Сердце Скорпиона — центр созвездия.",
            "Имеет голубой компаньон — Антарес B.",
            "Взорвётся как сверхновая в ближайшие 10 000 лет."
        ]
    },
    "Спика": {
        order: 17,
        type: "Голубой гигант (B1III-IV)",
        radius: 7.47,
        mass: 11.43,
        luminosity: 20500,
        temperature: 25300,
        distance: 250,
        age: 0.013,
        color: "#A8D0FF",
        coronaColor: "#8ABFFF",
        spectralClass: "B1III-IV",
        constellation: "Дева",
        info: {
            diameter: "10 400 000 км",
            diamSun: "7.5",
            mass: "2.27 × 10³¹ кг",
            massSun: "11.4",
            luminosity: "7.85 × 10³⁰ Вт",
            lumSun: "20 500",
            temperature: "25 300 K",
            tempClass: "Голубой",
            density: "0.04 г/см³",
            gravity: "562 м/с²",
            rotation: "4 дня",
            age: "13 млн лет",
            dist: "250 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Спика — тесная двойная система с периодом 4 дня.",
            "Пятнадцатая по яркости звезда ночного неба.",
            "Гиппарх открыл прецессию, наблюдая Спику.",
            "Название означает «колос пшеницы» на латыни.",
            "Звёзды так близки, что деформируют друг друга."
        ]
    },
    "Поллукс": {
        order: 18,
        type: "Оранжевый гигант (K0III)",
        radius: 8.8,
        mass: 1.91,
        luminosity: 32.7,
        temperature: 4666,
        distance: 33.78,
        age: 0.724,
        color: "#FFB366",
        coronaColor: "#FF9933",
        spectralClass: "K0III",
        constellation: "Близнецы",
        info: {
            diameter: "12 300 000 км",
            diamSun: "8.8",
            mass: "3.80 × 10³⁰ кг",
            massSun: "1.91",
            luminosity: "1.25 × 10²⁸ Вт",
            lumSun: "32.7",
            temperature: "4 666 K",
            tempClass: "Оранжевый",
            density: "0.004 г/см³",
            gravity: "6.8 м/с²",
            rotation: "~558 дней",
            age: "724 млн лет",
            dist: "34 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Поллукс — ближайший к Солнцу оранжевый гигант.",
            "Имеет подтверждённую экзопланету — Поллукс b.",
            "Семнадцатая по яркости звезда ночного неба.",
            "Вместе с Кастором образует «голову» Близнецов.",
            "Назван в честь одного из братьев-Диоскуров."
        ]
    },
    "Фомальгаут": {
        order: 19,
        type: "Белая звезда главной последовательности (A3V)",
        radius: 1.842,
        mass: 1.92,
        luminosity: 16.63,
        temperature: 8590,
        distance: 25.13,
        age: 0.44,
        color: "#E0EFFF",
        coronaColor: "#C0DFFF",
        spectralClass: "A3V",
        constellation: "Южная Рыба",
        info: {
            diameter: "2 570 000 км",
            diamSun: "1.84",
            mass: "3.82 × 10³⁰ кг",
            massSun: "1.92",
            luminosity: "6.37 × 10²⁷ Вт",
            lumSun: "16.6",
            temperature: "8 590 K",
            tempClass: "Белый",
            density: "0.43 г/см³",
            gravity: "174 м/с²",
            rotation: "~1 дня",
            age: "440 млн лет",
            dist: "25 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Фомальгаут — одна из «королевских звёзд» древней Персии.",
            "Окружена впечатляющим пылевым диском.",
            "Первая звезда с сфотографированной экзопланетой (Дагон).",
            "Название означает «рот рыбы» на арабском.",
            "Восемнадцатая по яркости звезда ночного неба."
        ]
    },
    "Денеб": {
        order: 20,
        type: "Белый сверхгигант (A2Ia)",
        radius: 203,
        mass: 19,
        luminosity: 196000,
        temperature: 8525,
        distance: 2615,
        age: 0.01,
        color: "#E8F0FF",
        coronaColor: "#D0E4FF",
        spectralClass: "A2Ia",
        constellation: "Лебедь",
        info: {
            diameter: "283 000 000 км",
            diamSun: "203",
            mass: "3.78 × 10³¹ кг",
            massSun: "19",
            luminosity: "7.51 × 10³¹ Вт",
            lumSun: "196 000",
            temperature: "8 525 K",
            tempClass: "Белый",
            density: "0.000006 г/см³",
            gravity: "1.3 м/с²",
            rotation: "~220 дней",
            age: "10 млн лет",
            dist: "2 615 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Денеб — одна из самых далёких звёзд, видимых невооружённым глазом.",
            "Абсолютная светимость в 196 000 раз больше Солнца.",
            "Если бы был на месте Сириуса, светил бы как полная Луна.",
            "Одна из вершин Летне-осеннего треугольника.",
            "Название означает «хвост» (курицы/лебедя) на арабском."
        ]
    },
    "Мимоза": {
        order: 21,
        type: "Голубой гигант (B0.5III)",
        radius: 8.4,
        mass: 16,
        luminosity: 34000,
        temperature: 27000,
        distance: 280,
        age: 0.01,
        color: "#A5CFFF",
        coronaColor: "#85BAFF",
        spectralClass: "B0.5III",
        constellation: "Южный Крест",
        info: {
            diameter: "11 700 000 км",
            diamSun: "8.4",
            mass: "3.18 × 10³¹ кг",
            massSun: "16",
            luminosity: "1.30 × 10³¹ Вт",
            lumSun: "34 000",
            temperature: "27 000 K",
            tempClass: "Голубой",
            density: "0.04 г/см³",
            gravity: "620 м/с²",
            rotation: "~3 дня",
            age: "10 млн лет",
            dist: "280 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Мимоза — вторая по яркости звезда Южного Креста.",
            "Переменная звезда типа Бета Цефея.",
            "Двадцатая по яркости звезда ночного неба.",
            "Также известна как Бекрукс (Бета Южного Креста).",
            "Изображена на многих флагах южного полушария."
        ]
    },
    "Регул": {
        order: 22,
        type: "Голубовато-белая звезда (B8IVn)",
        radius: 3.092,
        mass: 3.8,
        luminosity: 316,
        temperature: 12460,
        distance: 79.3,
        age: 0.314,
        color: "#C0DCFF",
        coronaColor: "#A0CBFF",
        spectralClass: "B8IVn",
        constellation: "Лев",
        info: {
            diameter: "4 300 000 км",
            diamSun: "3.09",
            mass: "7.56 × 10³⁰ кг",
            massSun: "3.8",
            luminosity: "1.21 × 10²⁹ Вт",
            lumSun: "316",
            temperature: "12 460 K",
            tempClass: "Голубовато-белый",
            density: "0.18 г/см³",
            gravity: "109 м/с²",
            rotation: "15.9 часов",
            age: "314 млн лет",
            dist: "79 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Регул — «маленький царь», сердце Льва.",
            "Четверная звёздная система.",
            "Вращается так быстро, что почти разрывается на части.",
            "Одна из четырёх «королевских звёзд» древности.",
            "Двадцать первая по яркости звезда ночного неба."
        ]
    },
    "Адара": {
        order: 23,
        type: "Голубой гигант (B2Iab)",
        radius: 13.9,
        mass: 12.6,
        luminosity: 38700,
        temperature: 21900,
        distance: 430,
        age: 0.022,
        color: "#AAD0FF",
        coronaColor: "#8ABDFF",
        spectralClass: "B2Iab",
        constellation: "Большой Пёс",
        info: {
            diameter: "19 400 000 км",
            diamSun: "13.9",
            mass: "2.51 × 10³¹ кг",
            massSun: "12.6",
            luminosity: "1.48 × 10³¹ Вт",
            lumSun: "38 700",
            temperature: "21 900 K",
            tempClass: "Голубой",
            density: "0.006 г/см³",
            gravity: "179 м/с²",
            rotation: "~10 дней",
            age: "22 млн лет",
            dist: "430 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Адара — вторая по яркости звезда Большого Пса после Сириуса.",
            "Один из мощнейших источников ультрафиолета на небе.",
            "Была самой яркой звездой на небе 4.7 млн лет назад.",
            "Двадцать вторая по яркости звезда ночного неба.",
            "Название означает «девы» на арабском."
        ]
    },
    "Гакрукс": {
        order: 24,
        type: "Красный гигант (M3.5III)",
        radius: 84,
        mass: 1.5,
        luminosity: 1500,
        temperature: 3626,
        distance: 88.6,
        age: 1.0,
        color: "#FF7755",
        coronaColor: "#FF5533",
        spectralClass: "M3.5III",
        constellation: "Южный Крест",
        info: {
            diameter: "117 000 000 км",
            diamSun: "84",
            mass: "2.98 × 10³⁰ кг",
            massSun: "1.5",
            luminosity: "5.75 × 10²⁹ Вт",
            lumSun: "1 500",
            temperature: "3 626 K",
            tempClass: "Красный",
            density: "0.00003 г/см³",
            gravity: "0.58 м/с²",
            rotation: "~650 дней",
            age: "1 млрд лет",
            dist: "89 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Гакрукс — третья по яркости звезда Южного Креста.",
            "Единственная красная звезда в Южном Кресте.",
            "Название — сокращение от «Гамма Южного Креста».",
            "Хорошо видна в южном полушарии.",
            "Ближайшая красная гигантская звезда к Солнцу."
        ]
    },
    "Кастор": {
        order: 25,
        type: "Белая звезда (A1V + A2Vm)",
        radius: 2.089,
        mass: 2.76,
        luminosity: 52.4,
        temperature: 10286,
        distance: 51,
        age: 0.37,
        color: "#D8EBFF",
        coronaColor: "#C0DFFF",
        spectralClass: "A1V",
        constellation: "Близнецы",
        info: {
            diameter: "2 910 000 км",
            diamSun: "2.09",
            mass: "5.49 × 10³⁰ кг",
            massSun: "2.76",
            luminosity: "2.01 × 10²⁸ Вт",
            lumSun: "52.4",
            temperature: "10 286 K",
            tempClass: "Белый",
            density: "0.48 г/см³",
            gravity: "174 м/с²",
            rotation: "~1 дня",
            age: "370 млн лет",
            dist: "51 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Кастор — секступольная звёздная система из 6 звёзд!",
            "Вместе с Поллуксом образует созвездие Близнецов.",
            "Назван в честь смертного из братьев-Диоскуров.",
            "Двадцать третья по яркости звезда ночного неба.",
            "Один из первых открытых визуальных двойных объектов."
        ]
    },
    "Шаула": {
        order: 26,
        type: "Голубой субгигант (B2IV)",
        radius: 6.2,
        mass: 14.5,
        luminosity: 36300,
        temperature: 25000,
        distance: 570,
        age: 0.015,
        color: "#A8D2FF",
        coronaColor: "#88BFFF",
        spectralClass: "B2IV",
        constellation: "Скорпион",
        info: {
            diameter: "8 600 000 км",
            diamSun: "6.2",
            mass: "2.88 × 10³¹ кг",
            massSun: "14.5",
            luminosity: "1.39 × 10³¹ Вт",
            lumSun: "36 300",
            temperature: "25 000 K",
            tempClass: "Голубой",
            density: "0.09 г/см³",
            gravity: "1030 м/с²",
            rotation: "~3 дня",
            age: "15 млн лет",
            dist: "570 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Шаула — жало Скорпиона, кончик его хвоста.",
            "Тройная звёздная система.",
            "Двадцать четвёртая по яркости звезда ночного неба.",
            "Название происходит от арабского «поднятый хвост».",
            "Одна из самых горячих звёзд, видимых невооружённым глазом."
        ]
    },
    "Беллатрикс": {
        order: 27,
        type: "Голубой гигант (B2III)",
        radius: 5.75,
        mass: 8.6,
        luminosity: 9211,
        temperature: 21800,
        distance: 250,
        age: 0.025,
        color: "#B0D4FF",
        coronaColor: "#90C2FF",
        spectralClass: "B2III",
        constellation: "Орион",
        info: {
            diameter: "8 000 000 км",
            diamSun: "5.75",
            mass: "1.71 × 10³¹ кг",
            massSun: "8.6",
            luminosity: "3.53 × 10³⁰ Вт",
            lumSun: "9 211",
            temperature: "21 800 K",
            tempClass: "Голубой",
            density: "0.06 г/см³",
            gravity: "712 м/с²",
            rotation: "~5 дней",
            age: "25 млн лет",
            dist: "250 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Беллатрикс — «воительница» на латыни, левое плечо Ориона.",
            "Одна из самых горячих звёзд, видимых невооружённым глазом.",
            "Третья по яркости звезда в созвездии Ориона.",
            "Также называется «Звезда Амазонок».",
            "Станет оранжевым гигантом через несколько миллионов лет."
        ]
    },
    "Эль-Нат": {
        order: 28,
        type: "Голубой гигант (B7III)",
        radius: 4.2,
        mass: 5.0,
        luminosity: 700,
        temperature: 13600,
        distance: 134,
        age: 0.1,
        color: "#B8DAFF",
        coronaColor: "#98CAFF",
        spectralClass: "B7III",
        constellation: "Телец",
        info: {
            diameter: "5 850 000 км",
            diamSun: "4.2",
            mass: "9.95 × 10³⁰ кг",
            massSun: "5.0",
            luminosity: "2.68 × 10²⁹ Вт",
            lumSun: "700",
            temperature: "13 600 K",
            tempClass: "Голубой",
            density: "0.10 г/см³",
            gravity: "775 м/с²",
            rotation: "~1 дня",
            age: "100 млн лет",
            dist: "134 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Эль-Нат — второй рог Тельца.",
            "Раньше принадлежала созвездию Возничего (Гамма Возничего).",
            "Название означает «бодающий» на арабском.",
            "Двадцать седьмая по яркости звезда ночного неба.",
            "Богата марганцем и бедна кальцием и магнием."
        ]
    },
    "Мирах": {
        order: 29,
        type: "Красный гигант (M0III)",
        radius: 70,
        mass: 2.49,
        luminosity: 1995,
        temperature: 3842,
        distance: 197,
        age: 3.0,
        color: "#FF8866",
        coronaColor: "#FF6644",
        spectralClass: "M0III",
        constellation: "Андромеда",
        info: {
            diameter: "97 500 000 км",
            diamSun: "70",
            mass: "4.95 × 10³⁰ кг",
            massSun: "2.49",
            luminosity: "7.64 × 10²⁹ Вт",
            lumSun: "1 995",
            temperature: "3 842 K",
            tempClass: "Красный",
            density: "0.00001 г/см³",
            gravity: "1.4 м/с²",
            rotation: "~2 года",
            age: "3 млрд лет",
            dist: "197 св. лет",
            composition: "Водород, Гелий"
        },
        facts: [
            "Мирах — пояс Андромеды.",
            "Используется как указатель на галактику Андромеды M31.",
            "Переменная звезда с небольшими колебаниями яркости.",
            "Название означает «пояс» на арабском.",
            "Примерно в 1995 раз ярче Солнца."
        ]
    },
    "Альнилам": {
        order: 30,
        type: "Голубой сверхгигант (B0Ia)",
        radius: 42,
        mass: 40,
        luminosity: 537000,
        temperature: 26500,
        distance: 2000,
        age: 0.004,
        color: "#A0CDFF",
        coronaColor: "#80BAFF",
        spectralClass: "B0Ia",
        constellation: "Орион",
        info: {
            diameter: "58 500 000 км",
            diamSun: "42",
            mass: "7.96 × 10³¹ кг",
            massSun: "40",
            luminosity: "2.06 × 10³² Вт",
            lumSun: "537 000",
            temperature: "26 500 K",
            tempClass: "Голубой",
            density: "0.0001 г/см³",
            gravity: "62 м/с²",
            rotation: "~4 дня",
            age: "4 млн лет",
            dist: "2 000 св. лет",
            composition: "Водород, Гелий, Азот"
        },
        facts: [
            "Альнилам — центральная и самая яркая звезда Пояса Ориона.",
            "Одна из самых мощных известных звёзд в Галактике.",
            "Теряет массу в миллион раз быстрее Солнца.",
            "Взорвётся как сверхновая через несколько миллионов лет.",
            "Название означает «нить жемчуга» на арабском."
        ]
    }
};

// Шкала температур и цветов звёзд
export const TEMPERATURE_SCALE = [
    { temp: 2000,  color: "#FF3300", label: "M (Красный)", desc: "Красные карлики и гиганты" },
    { temp: 3500,  color: "#FF5500", label: "K (Оранжевый)", desc: "Оранжевые звёзды" },
    { temp: 5000,  color: "#FFAA33", label: "G (Жёлтый)", desc: "Жёлтые карлики (как Солнце)" },
    { temp: 6000,  color: "#FFDDAA", label: "F (Жёлто-белый)", desc: "Жёлто-белые звёзды" },
    { temp: 7500,  color: "#FFFFFF", label: "A (Белый)", desc: "Белые звёзды" },
    { temp: 10000, color: "#CCDEFF", label: "B (Голубовато-белый)", desc: "Голубые гиганты" },
    { temp: 30000, color: "#99BBFF", label: "O (Голубой)", desc: "Горячие голубые звёзды" },
    { temp: 50000, color: "#7799FF", label: "O (Ультра-голубой)", desc: "Самые горячие звёзды" }
];