name: Deploy to GitHub Pages and VDS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Задача 1: Автоматическая отправка на ваш VDS сервер (mapruapp.ru)
  deploy-to-vds:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to VDS Nginx
        shell: powershell
        run: |
          Get-ChildItem -Path . -Exclude ".git", ".github" | Copy-Item -Destination "C:\www\vsemap" -Recurse -Force

  # Задача 2: Публикация на GitHub Pages (vsemap.ru)
  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4